---
AllCops:
  Exclude:
    - "node_modules/**/*"
    - "vendor/**/*"
    - "db/schema.rb"

#################### Layout ###########################

#################### Naming ##########################

#################### Style ###########################

Style/StringLiterals:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/Documentation:
  Enabled: false

#################### Metrics ###############################

Metrics/LineLength:
  Max: 120

#################### Lint ##################################

#################### Performance ###########################

#################### Rails #################################

Bundler/OrderedGems:
  Exclude:
    - 'Gemfile'
