---

#################### Layout ###########################

#################### Naming ##########################

#################### Style ###########################

Style/StringLiterals:
  Enabled: false

#################### Metrics ###############################

Metrics/LineLength:
  Max: 120

#################### Lint ##################################

#################### Performance ###########################

#################### Rails #################################
